name: CI/CD

on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD_KEY }}

      - name: Construir y Subir Imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pulloam/web-itierx:0.0.1
  deploy:
      needs: build-and-push
      runs-on: self-hosted  #nombre de label al ejecutar script de configuracion
      steps:
        - name: Ejecutar
          run: |
            docker pull pulloam/web-itierx:0.0.1
            docker stop web-itierx || true
            docker rm web-itierx || true
            docker run --name web-itierx --restart unless-stopped -d -p 18080:80 pulloam/web-itierx:0.0.1
            docker image prune -f
